### ISSUE TITLE
"Error: Client is not created" after client._destroy()

### ISSUE THREAD

**Issue by julestechting** [nodegin/tglib#37]
Every time I use client._destroy(), I have the following exception thrown:
`(node:20) UnhandledPromiseRejectionWarning: Error: Client is not created
    at Promise (<path>/node_modules/tglib/Client.js:314:23)
    at new Promise (<anonymous>)
    at Client._receive (<path>/node_modules/tglib/Client.js:312:12)
    at Client.loop (<path>/node_modules/tglib/Client.js:112:31)
    at Client.loop (<path>/node_modules/tglib/Client.js:128:10)`
I seems that while the TDLIB client is deleted, the loop function is still running and tries to fetch updates.
How to avoid this issue? Can the loop be stopped?

**Comment by nodegin** [comment]
Fixed in v2.1

**Comment by julestechting** [comment]
Amazing! I'll test it today. Thank you, @nodegin!
